# Generated by Django 3.2 on 2021-08-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['addedOn']},
        ),
    ]
