# Generated by Django 3.1.1 on 2020-09-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistening_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='auctionlistening',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
