# Generated by Django 3.1.1 on 2020-09-25 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200924_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistening',
            name='favoured',
            field=models.ManyToManyField(blank=True, related_name='user_favoured', to=settings.AUTH_USER_MODEL),
        ),
    ]
