# Generated by Django 3.1.1 on 2020-09-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200926_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
